(define (complex x y) (cons x y))
(define (c-re c) (car c))
(define (c-im c) (cdr c))
(define (c-= c1 c2)
  (and (= (c-re c1) (c-re c2)) (= (c-im c1) (c-im c2))))
(define (c-+ c1 c2)
  (complex (+ (c-re c1) (c-re c2)) (+ (c-im c1) (c-im c2))))
(define (c-* c1 c2)
  (complex (- (* (c-re c1) (c-re c2)) (* (c-im c1) (c-im c2)))
	   (+ (* (c-re c1) (c-im c2)) (* (c-im c1) (c-re c2)))))
